### PR TITLE
Fix path issue in Scalar config

### LINKED ISSUE #151: Swagger path responds with `NOT_FOUND`.
It worked using `elysia@1.0.15` and `@elysiajs/swagger@^1.0.2`.

My dependencies:
```
  "dependencies": {
    "@apollo/client": "^3.11.8",
    "@bogeychan/elysia-logger": "^0.1.4",
    "@elysiajs/bearer": "^1.1.2",
    "@elysiajs/cors": "^1.1.1",
    "@elysiajs/html": "^1.1.1",
    "@elysiajs/jwt": "^1.1.1",
    "@elysiajs/static": "^1.1.1",
    "@elysiajs/swagger": "^1.1.3",
    "@octokit/graphql-schema": "^15.25.0",
    "drizzle-orm": "^0.33.0",
    "elysia": "^1.1.17",
    "graphql": "^16.9.0",
    "octokit": "^4.0.2",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@biomejs/biome": "^1.9.2",
    "@octokit/types": "^13.6.0",
    "@types/html-validator": "^5.0.6",
    "@types/pg": "^8.11.10",
    "bun-types": "^1.1.29",
    "drizzle-kit": "^0.24.2",
    "html-validator": "^6.0.1"
  },
```
  
Old dependencies:
```
  "dependencies": {
    "@bogeychan/elysia-logger": "^0.0.20",
    "@elysiajs/bearer": "^1.0.2",
    "@elysiajs/cors": "^1.0.2",
    "@elysiajs/html": "^1.0.2",
    "@elysiajs/jwt": "^1.0.2",
    "@elysiajs/static": "^1.0.2",
    "@elysiajs/swagger": "^1.0.2",
    "@octokit/graphql-schema": "^14.47.1",
    "drizzle-orm": "^0.30.9",
    "elysia": "^1.0.9",
    "octokit": "^3.1.2",
    "pg": "^8.11.5"
  },
  "devDependencies": {
    "@biomejs/biome": "^1.6.1",
    "@octokit/types": "^12.6.0",
    "@types/html-validator": "^5.0.6",
    "@types/pg": "^8.11.5",
    "bun-types": "^1.0.33",
    "drizzle-kit": "^0.20.17",
    "html-validator": "^6.0.1"
  },
```

### LINKED ISSUE #157: Elysia.js Swagger Doesn't Work On Next.js
image
image
image

I can't arrive the swagger page but the ironic thing is everything is okay!!
I'm trying to implement Elysia.js to next.js but my swagger plugin is sending request to /swagger/json path. But the json file is under the /api/swagger/json

How can I fix it?

### LINKED ISSUE #161: OpenAPI spec wrong URL
I was using Traefik with these match rules.

```
Host(`domain.com`) && PathPrefix (`/api`)
```

This will route all `domain.com` with the prefix `/api` to the desired service which is our backend running Elysia with swagger. With #16 it was fixed to use the prefix from Elysia configuration, but on the latest version the Swagger option url is in the wrong url. (Does not respect prefix at all).

### LINKED ISSUE #183: /swagger/json returning 404 if Swagger is used in conjunction with a prefix set in Elysia
When setting a prefix in Elysia and simultaneously using Swagger, it fails to correctly load `/swagger/json`.

To reproduce:

```js
new Elysia({ prefix: '/v1' })
	.use(swagger())
	.use(logixlysia()) // logger used to highlight responses on console
	.get('/', () => 'Hello!')
	.listen(3000);
```

Visit the server in a browser `http://localhost:3000/v1/swagger` and you'll be presented with the UI theme of Scalar, but no content.

Adding a logger reveals that `/v1/swagger` gets hit and returns a 200 status, immediately followed by `/swagger/json` (note the lack of prefix) getting hit with a 404 status.

It seems this has been attempted to be fixed before #16 but has remained an ongoing issue since at least October 2024.

image
image

### PR DESCRIPTION
**Pull request by bhaleraosaurabh**
When using a prefix, the plugin tries to fetch the scalar config from an incorrect path as mentioned in issues #161, #183, #151 . This can be seen in the screenshots below.

This PR enables successful fetching of the Scalar config from the correct URL whether a prefix is used or not and even if the prefix is nested.

closes #161 
closes #183 
closes #151 
closes #157 

elysia with prefix
Incorrect JSON path

No prefix
No prefix on elysia

Elysia swagger with corrected path
nested prefix

### CODE REVIEW

**Comment by antoniel** [comment]
+1

**Comment by dodas** [comment]
bump. this fixes my issue when Scalar UI tries to load the openapi schema from `/swagger/json`, even though it should be requesting `/api/swagger/json`.
cc @SaltyAom

File: src/index.ts [hunk 1]
```diff
@@ -85,7 +85,7 @@ export const swagger = async <Path extends string = '/swagger'>(
 		const scalarConfiguration: ReferenceConfiguration = {
 			spec: {
 				...scalarConfig.spec,
-				url: openAPISpecUrl
+				url: `${request.url}/json`
```
Comment (dodas) [inline src/index.ts:88]: This has 2 potential problems:
- if the swagger UI url includes trailing slash, the spec url will contain `//json`
- in some cases (e.g. behind reverse proxies), the hostname as well as the protocol is not actually correct in `request.url` and you can only rely on `pathname` being correct.
```suggestion
				url: `${new URL(request.url).pathname.replace(/\/$/, "")}/json`
```

**Review by dodas — APPROVED** [review]

**Comment by bhaleraosaurabh** [comment]
Could we please have it merged @SaltyAom ?

**Comment by ortonomy** [comment]
This got merged, but it's still not working in Elysia 1.3.1 and this package 1.3.0

**Comment by madkarmaa** [comment]
Still not working as it should, have to resort to [this workaround](https://github.com/elysiajs/elysia/issues/1071#issuecomment-2673960231).

- **Bun version**: 1.2.17
- **ElysiaJS version**: `1.3.5`
- **`@elysiajs/swagger` version**: `1.3.0`
